"""
Data Service
------------
Loads the synthetic dataset generated by data/generate_data.py into memory
once at startup. Standing in for a real database in this portfolio project
- swapping this for a Postgres/Mongo-backed repository would not require
any changes to the recommendation engine or API route logic.
"""

import json
import os
from typing import List, Dict, Any, Optional

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")


class DataService:
    def __init__(self):
        self.products: List[Dict[str, Any]] = []
        self.users: List[Dict[str, Any]] = []
        self._load()

    def _load(self):
        products_path = os.path.join(DATA_DIR, "products.json")
        users_path = os.path.join(DATA_DIR, "users.json")
        with open(products_path) as f:
            self.products = json.load(f)
        with open(users_path) as f:
            self.users = json.load(f)

    def get_products(self) -> List[Dict[str, Any]]:
        return self.products

    def get_product(self, product_id: int) -> Optional[Dict[str, Any]]:
        return next((p for p in self.products if p["id"] == product_id), None)

    def get_users(self) -> List[Dict[str, Any]]:
        return self.users

    def get_user(self, user_id: int) -> Optional[Dict[str, Any]]:
        return next((u for u in self.users if u["id"] == user_id), None)

    def categories(self) -> List[str]:
        return sorted({p["category"] for p in self.products})

    def brands(self) -> List[str]:
        return sorted({p["brand"] for p in self.products})


# Singleton instance shared across the app (simple pattern appropriate for
# an in-memory, read-mostly dataset).
data_service = DataService()
